##
## This Dockerfile is used for creating the application to be deployed.
##

FROM nciwebcomm/dotnet-docker:runtime

ARG version_number
RUN curl -SL "https://github.com/NCIOCPL/bestbets-api/releases/download/$version_number/bestbets-indexer-$version_number.zip"  --output bestbets-indexer.zip \
    && mkdir -p /usr/share/release \
    && unzip bestbets-indexer.zip  -d /usr/share/release
WORKDIR /usr/share/release
ENTRYPOINT ["dotnet", "NCI.OCPL.Api.BestBets.Indexer.dll"]
