##
## This Dockerfile is used for creating the application to be deployed.
##

FROM nciwebcomm/dotnet-docker:runtime

COPY . /app

WORKDIR /app

RUN ["dotnet", "restore"]

RUN ["dotnet", "build"]

EXPOSE 5000/tcp

CMD ["dotnet", "run", "--server.urls", "http://*:5000"]
